services:
  db:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  django:
    build: .
    container_name: django_app
    command: >
      sh -c "
        ./wait-for-it.sh db:5432 -- 
        ./wait-for-it.sh redis:6379 -- 
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn travel.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery:
    build: .
    container_name: celery_worker
    command: >
      sh -c "
        ./wait-for-it.sh db:5432 -- 
        ./wait-for-it.sh redis:6379 -- 
        celery -A travel worker -l info
      "
    env_file:
      - .env
    depends_on:
      - django
      - db
      - redis
    restart: unless-stopped

volumes:
  pgdata:
