# Generated by Django 5.2.6 on 2025-10-05 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_details_booking_idempotency_key_booking_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='safaris/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
